version: '3'

services:

  # API CYMIT QUIMICA
  api:
    build: python/
    command: python crawler.py https://www.larodan.com/products/category/monounsaturated-fa/ -c 5
    volumes:
      - ../app:/app/
